// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/backend.dart';
import 'api/simple.dart';
import 'dart:async';
import 'dart:convert';
import 'dart:ffi' as ffi;
import 'database/app_settings.dart';
import 'database/comic_chapter.dart';
import 'database/comic_image.dart';
import 'database/reader_settings.dart';
import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_io.dart';

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw);

  @protected
  RustStreamSink<String> dco_decode_StreamSink_String_Sse(dynamic raw);

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  AppSettings dco_decode_app_settings(dynamic raw);

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  AppSettings dco_decode_box_autoadd_app_settings(dynamic raw);

  @protected
  ComicInfo dco_decode_box_autoadd_comic_info(dynamic raw);

  @protected
  ReaderSettings dco_decode_box_autoadd_reader_settings(dynamic raw);

  @protected
  ComicChapter dco_decode_comic_chapter(dynamic raw);

  @protected
  ComicImage dco_decode_comic_image(dynamic raw);

  @protected
  ComicInfo dco_decode_comic_info(dynamic raw);

  @protected
  int dco_decode_i_32(dynamic raw);

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw);

  @protected
  List<String> dco_decode_list_String(dynamic raw);

  @protected
  List<ComicChapter> dco_decode_list_comic_chapter(dynamic raw);

  @protected
  List<ComicImage> dco_decode_list_comic_image(dynamic raw);

  @protected
  List<ComicInfo> dco_decode_list_comic_info(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  ComicInfo? dco_decode_opt_box_autoadd_comic_info(dynamic raw);

  @protected
  ReaderSettings? dco_decode_opt_box_autoadd_reader_settings(dynamic raw);

  @protected
  ReaderSettings dco_decode_reader_settings(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer);

  @protected
  RustStreamSink<String> sse_decode_StreamSink_String_Sse(
    SseDeserializer deserializer,
  );

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  AppSettings sse_decode_app_settings(SseDeserializer deserializer);

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  AppSettings sse_decode_box_autoadd_app_settings(SseDeserializer deserializer);

  @protected
  ComicInfo sse_decode_box_autoadd_comic_info(SseDeserializer deserializer);

  @protected
  ReaderSettings sse_decode_box_autoadd_reader_settings(
    SseDeserializer deserializer,
  );

  @protected
  ComicChapter sse_decode_comic_chapter(SseDeserializer deserializer);

  @protected
  ComicImage sse_decode_comic_image(SseDeserializer deserializer);

  @protected
  ComicInfo sse_decode_comic_info(SseDeserializer deserializer);

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer);

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer);

  @protected
  List<ComicChapter> sse_decode_list_comic_chapter(
    SseDeserializer deserializer,
  );

  @protected
  List<ComicImage> sse_decode_list_comic_image(SseDeserializer deserializer);

  @protected
  List<ComicInfo> sse_decode_list_comic_info(SseDeserializer deserializer);

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  ComicInfo? sse_decode_opt_box_autoadd_comic_info(
    SseDeserializer deserializer,
  );

  @protected
  ReaderSettings? sse_decode_opt_box_autoadd_reader_settings(
    SseDeserializer deserializer,
  );

  @protected
  ReaderSettings sse_decode_reader_settings(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  void sse_encode_AnyhowException(
    AnyhowException self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_StreamSink_String_Sse(
    RustStreamSink<String> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_app_settings(AppSettings self, SseSerializer serializer);

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_app_settings(
    AppSettings self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_comic_info(
    ComicInfo self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_reader_settings(
    ReaderSettings self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_comic_chapter(ComicChapter self, SseSerializer serializer);

  @protected
  void sse_encode_comic_image(ComicImage self, SseSerializer serializer);

  @protected
  void sse_encode_comic_info(ComicInfo self, SseSerializer serializer);

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer);

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer);

  @protected
  void sse_encode_list_comic_chapter(
    List<ComicChapter> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_comic_image(
    List<ComicImage> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_comic_info(
    List<ComicInfo> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_comic_info(
    ComicInfo? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_reader_settings(
    ReaderSettings? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_reader_settings(
    ReaderSettings self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);
}

// Section: wire_class

class RustLibWire implements BaseWire {
  factory RustLibWire.fromExternalLibrary(ExternalLibrary lib) =>
      RustLibWire(lib.ffiDynamicLibrary);

  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
  _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  RustLibWire(ffi.DynamicLibrary dynamicLibrary)
    : _lookup = dynamicLibrary.lookup;
}
