// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'app_settings.freezed.dart';

@freezed
sealed class AppSettings with _$AppSettings {
  const factory AppSettings({
    required PlatformInt64 id,
    required String theme,
    required String darkTheme,
    required bool copySkipConfirm,
    required String copyComicTitleTemplate,
    required bool autoFullScreenIntoReader,
    required String bookListType,
    required int fontScalePercent,
    required int coverWidth,
    required int coverHeight,
    required bool annotation,
    required bool fullScreenRemoveBars,
    required bool enableVolumeControl,
  }) = _AppSettings;
}
