// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'comic_image.freezed.dart';

@freezed
sealed class ComicImage with _$ComicImage {
  const factory ComicImage({
    required String id,
    required String comicId,
    required String chapterId,
    required int indexInChapter,
    required String path,
    required int width,
    required int height,
    required String format,
    required String status,
  }) = _ComicImage;
}
