// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

class ReaderSettings {
  final PlatformInt64 id;
  final String settingsType;
  final String comicId;
  final String templateName;
  final PlatformInt64 backgroundColor;
  final String readerType;
  final String touchType;
  final String readerDirection;
  final String imageFilter;
  final PlatformInt64 marginTop;
  final PlatformInt64 marginBottom;
  final PlatformInt64 marginLeft;
  final PlatformInt64 marginRight;
  final bool enableVolumeControl;
  final bool annotation;
  final String scrollType;
  final PlatformInt64 scrollPercent;

  const ReaderSettings({
    required this.id,
    required this.settingsType,
    required this.comicId,
    required this.templateName,
    required this.backgroundColor,
    required this.readerType,
    required this.touchType,
    required this.readerDirection,
    required this.imageFilter,
    required this.marginTop,
    required this.marginBottom,
    required this.marginLeft,
    required this.marginRight,
    required this.enableVolumeControl,
    required this.annotation,
    required this.scrollType,
    required this.scrollPercent,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      settingsType.hashCode ^
      comicId.hashCode ^
      templateName.hashCode ^
      backgroundColor.hashCode ^
      readerType.hashCode ^
      touchType.hashCode ^
      readerDirection.hashCode ^
      imageFilter.hashCode ^
      marginTop.hashCode ^
      marginBottom.hashCode ^
      marginLeft.hashCode ^
      marginRight.hashCode ^
      enableVolumeControl.hashCode ^
      annotation.hashCode ^
      scrollType.hashCode ^
      scrollPercent.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ReaderSettings &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          settingsType == other.settingsType &&
          comicId == other.comicId &&
          templateName == other.templateName &&
          backgroundColor == other.backgroundColor &&
          readerType == other.readerType &&
          touchType == other.touchType &&
          readerDirection == other.readerDirection &&
          imageFilter == other.imageFilter &&
          marginTop == other.marginTop &&
          marginBottom == other.marginBottom &&
          marginLeft == other.marginLeft &&
          marginRight == other.marginRight &&
          enableVolumeControl == other.enableVolumeControl &&
          annotation == other.annotation &&
          scrollType == other.scrollType &&
          scrollPercent == other.scrollPercent;
}
